name: source check

on:
    push:
        branches: [main]

jobs:
    source-check:
        name: Execute Source Check
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
              with:
                  version: latest
            - uses: actions/setup-node@v4
              with:
                  node-version: "22"
                  cache: "pnpm"

            - name: Run Installation
              run: pnpm install

            - name: Run Source Check
              run: pnpm run src-check
